/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js.
// It is included here to ensure TypeScript picks up Next/React JSX types.
// Do not edit this file.

